apiVersion: apps/v1
kind: Deployment
metadata:
  name: timer
  labels:
    app: timer
spec:
  selector:
    matchLabels:
      app: timer
  replicas: 1
  template:
    metadata:
      labels:
        app: timer
    spec:
      containers:
      - name: timer
        image: gcr.io/zeebe-io/starter:zeebe
        imagePullPolicy: Always
        env:
          - name: JAVA_OPTIONS
            value: >-
              -Dapp.brokerUrl=np-disable-wal-4-zeebe-gateway:26500
              -Dapp.starter.rate=300
              -Dzeebe.client.requestTimeout=62000
              -XX:+HeapDumpOnOutOfMemoryError
              -Dapp.starter.bpmnXmlPath=bpmn/timerProcess.bpmn
              -Dapp.starter.processId=timerProcess
          - name: LOG_LEVEL
            value: "warn"
        resources:
          limits:
            cpu: 2
            memory: 2Gi
          requests:
            cpu: 2
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: zeebe
    app.kubernetes.io/instance: np-disable-wal-4
    app.kubernetes.io/name: zeebe-cluster
  name: timer
spec:
  clusterIP: None
  ports:
  - name: http
    port: 9600
    protocol: TCP
    targetPort: 9600
  publishNotReadyAddresses: true
  selector:
    app: timer
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
